In [1]:
import numpy as np

In [7]:
arr=np.array([12,23,34,45,56.88])

In [8]:
arr

array([12.  , 23.  , 34.  , 45.  , 56.88])

In [9]:
print(arr)

[12.   23.   34.   45.   56.88]


In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.dtype

dtype('float64')

In [15]:
%%timeit
arr=np.array([12,23,34,45,56.88,'Swarali'])

2.06 µs ± 63.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
arr

array(['12', '23', '34', '45', '56.88', 'Swarali'], dtype='<U32')

In [17]:
arr.dtype

dtype('<U32')

In [18]:
%%timeit
arr=np.array([12,23,34,45,56.88,'Swarali'])

2.02 µs ± 33 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
arr[3]

'45'

In [20]:
arr.shape

(6,)

In [21]:
arr=np.array([12,23,34,45,56.88])

In [22]:
arr*2

array([ 24.  ,  46.  ,  68.  ,  90.  , 113.76])

In [23]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
#2d

In [30]:
arr1=np.array([[1,2,3],[5,6,7],[9,9,0]])

In [31]:
arr1

array([[1, 2, 3],
       [5, 6, 7],
       [9, 9, 0]])

In [32]:
arr1.shape

(3, 3)

In [33]:
arr1.ndim

2

In [35]:
arr1.flatten()

array([1, 2, 3, 5, 6, 7, 9, 9, 0])

In [41]:
arr1.reshape(3,-1,2)

ValueError: cannot reshape array of size 9 into shape (3,newaxis,2)

In [42]:
arr1[0:3,0:2]

array([[1, 2],
       [5, 6],
       [9, 9]])

In [43]:
arr


array([12.  , 23.  , 34.  , 45.  , 56.88])

In [45]:
arr.mean()

34.176

In [46]:
arr.min()

12.0

In [47]:
np.unique(arr)

array([12.  , 23.  , 34.  , 45.  , 56.88])

In [50]:
np.linalg.det(arr)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional